DELETE FROM public.wiki_articles WHERE id IS NOT NULL;

INSERT INTO public.wiki_articles (slug, title, category, excerpt, content, published, sort_order) VALUES
('getting-started', 'Getting Started on Warden Network', 'Start Here', 'Join the server, set up your account and take your first steps in under five minutes.',
E'Welcome to Warden Network. This page takes you from a fresh install to your first base.\n\n## Joining the server\n\n1. Launch Minecraft: Java Edition (latest release recommended).\n2. Open **Multiplayer → Add Server**.\n3. Enter `play.warden.rip` as the address.\n4. Join and wait for the world to load.\n\nBedrock players can connect on the same address using the default Bedrock port.\n\n## Your first five minutes\n\n- Run `/spawn` at any time to return to the hub.\n- Pick a game mode from the compass in your hotbar.\n- Use `/rtp` to teleport to a random wild location away from spawn.\n- Set your home with `/sethome` before you log off.\n\n## Link your account\n\nLinking your Minecraft account to the website unlocks store purchases, rank sync and profile stats. Sign in at [warden.rip](https://warden.rip), open your profile and follow the link instructions. Linking Discord on the same page adds your in-game rank role automatically.\n\n## What to read next\n\n- [Server Rules](/wiki/rules) so you do not lose your progress.\n- [Essential Commands](/wiki/commands) for everyday play.\n- [Economy Basics](/wiki/economy) to start earning.', true, 1),

('rules', 'Server Rules', 'Start Here', 'The full rulebook: what gets you warned, muted, or banned, and how punishments escalate.',
E'These rules apply on every server, in Discord and on the website. Not knowing a rule is not a defence.\n\n## Core rules\n\n1. **No cheating.** Any client modification that gives an unfair advantage — killaura, reach, x-ray, autoclickers, fly, macros that automate gameplay — is banned.\n2. **No griefing or stealing** outside of designated PvP and raid zones.\n3. **Be civil.** No harassment, hate speech, slurs, threats or doxxing.\n4. **No spam or advertising.** This includes other server addresses, Discord invites and referral links.\n5. **No exploiting.** Duplication glitches and unintended mechanics must be reported, not used.\n6. **One account per player** unless staff grant an exception. Ban evasion with an alt extends the original ban.\n7. **Keep chat family friendly.** No explicit content, gore, or NSFW links or builds.\n8. **No scamming.** Trades are enforced as agreed; deliberate deception is punished.\n9. **Respect staff decisions.** Argue an appeal on the website, not in chat.\n\n## Punishment ladder\n\n| Offence | First | Second | Third |\n| --- | --- | --- | --- |\n| Chat violations | Warning | 1 day mute | 7 day mute |\n| Griefing | Rollback + 3 day ban | 14 day ban | Permanent |\n| Cheating | Permanent ban | — | — |\n| Exploiting | Item removal + 7 day ban | Permanent | — |\n\nStaff may adjust severity based on intent and history.\n\n## Appeals\n\nEvery punishment can be appealed once at [warden.rip/appeal](https://warden.rip/appeal). Be honest — accepted appeals are almost always the ones that admit what happened.', true, 2),

('commands', 'Essential Commands', 'Start Here', 'Every command a regular player needs, grouped by what it does.',
E'A reference of the commands available to all players. Rank-only commands are marked.\n\n## Movement and homes\n\n| Command | What it does |\n| --- | --- |\n| `/spawn` | Return to the main spawn |\n| `/sethome <name>` | Save a home point |\n| `/home <name>` | Teleport to a saved home |\n| `/delhome <name>` | Remove a home |\n| `/rtp` | Random teleport into the wild |\n| `/back` | Return to your previous location (rank perk) |\n\n## Teleporting to players\n\n| Command | What it does |\n| --- | --- |\n| `/tpa <player>` | Request to teleport to someone |\n| `/tpahere <player>` | Ask someone to come to you |\n| `/tpaccept` | Accept a pending request |\n| `/tpdeny` | Decline a pending request |\n| `/tptoggle` | Block all incoming requests |\n\n## Economy\n\n| Command | What it does |\n| --- | --- |\n| `/balance` | Check your coin balance |\n| `/pay <player> <amount>` | Send coins |\n| `/shop` | Open the server shop |\n| `/ah` | Open the player auction house |\n| `/sell hand` | Sell the item you are holding |\n\n## Social\n\n| Command | What it does |\n| --- | --- |\n| `/msg <player> <text>` | Private message |\n| `/r <text>` | Reply to the last message |\n| `/ignore <player>` | Mute a player for yourself |\n| `/party create` | Start a party |\n| `/party invite <player>` | Invite to your party |\n\n## Utility\n\n| Command | What it does |\n| --- | --- |\n| `/vote` | Get the voting links |\n| `/stats` | View your own statistics |\n| `/rank` | See your current rank and perks |\n| `/report <player> <reason>` | Report a rule breaker |\n| `/help` | In-game help menu |', true, 3),

('ranks', 'Ranks and Perks', 'Ranks', 'Guardian, Sentinel, Warden and Ascendant — what each rank includes and how upgrades work.',
E'Website ranks are permanent, activate the moment checkout completes and apply across every game mode.\n\n## The four ranks\n\n### Guardian\nThe entry rank. Coloured chat name, extra homes, `/back` after death, and access to the Guardian cosmetic kit.\n\n### Sentinel\nEverything in Guardian plus a larger home limit, shorter teleport cooldowns, `/craft` and `/enderchest` anywhere, and a monthly crate key.\n\n### Warden\nEverything in Sentinel plus priority queue access, a personal vault, the ability to set a nickname, and a larger auction house listing limit.\n\n### Ascendant\nThe top rank. Everything in Warden plus the largest home and vault limits, exclusive particle effects, early access to new game modes, and the Ascendant tag in chat and on the website.\n\n## Buying a rank\n\nRanks are sold at [warden.rip/store](https://warden.rip/store). Payment completes, the rank is granted instantly — no ticket, no waiting. If you already own a lower rank, the store applies upgrade pricing automatically so you never pay twice for the same perks.\n\n## Troubleshooting\n\nIf a rank has not appeared in game within a minute, relog once. If it still has not applied, open a ticket on the website with your order reference and it will be fixed manually.', true, 10),

('economy', 'Economy Basics', 'Gameplay', 'Coins, gems, shards, the shop and the auction house — how money works and how to make it.',
E'Warden Network runs a player-driven economy with two currencies.\n\n## Currencies\n\n- **Coins** are the in-game currency. Earn them by playing, selling to the shop, voting and trading with other players.\n- **Gems** and **Shards** are premium currencies bought from the store or awarded in events. They buy cosmetics, crate keys and convenience unlocks.\n\n## Making coins\n\n1. **Sell farm output.** Crops, mob drops and ores all have a shop price. `/sell hand` and `/sell all` are the fastest route.\n2. **Run the auction house.** Buy underpriced listings with `/ah` and relist at market value.\n3. **Vote daily.** Every vote pays coins and adds to your streak multiplier.\n4. **Complete events.** Weekly events pay out large coin prizes.\n\n## Spending wisely\n\n- Tools and armour from other players are usually cheaper than shop prices.\n- Prices move with supply — check `/ah` before dumping stock into the shop.\n- Keep a reserve. Auction sniping only works if you have liquid coins.\n\n## Trading safely\n\nUse the auction house whenever possible; it is the only trade method staff can verify. Hand trades are at your own risk and are not covered by scam reports unless you have clear video evidence.', true, 20),

('voting', 'Voting and Rewards', 'Gameplay', 'Where to vote, what you earn, and how vote streaks multiply your rewards.',
E'Voting is free, takes about a minute, and is the single best daily habit for a new player.\n\n## How to vote\n\nRun `/vote` in game or open [warden.rip/vote](https://warden.rip/vote) for the current list of voting sites. Enter your exact Minecraft username — a typo sends the reward to someone else.\n\n## Rewards\n\n- Coins on every vote\n- A vote key for the vote crate\n- Vote points, redeemable in the vote shop\n\n## Streaks\n\nVoting on consecutive days builds a streak. Higher streaks increase the coin payout and the odds of rare crate rolls. Missing a day resets the streak, so vote before you log off rather than after.\n\n## If a reward did not arrive\n\nVoting sites sometimes deliver late. Wait ten minutes, then relog — pending rewards are handed out on join. If it still has not arrived after an hour, open a support ticket with the site name and time you voted.', true, 21),

('events', 'Events and Seasons', 'Gameplay', 'Weekly events, seasonal resets and how the leaderboards and prizes work.',
E'Events are where the biggest prizes on the network live.\n\n## Weekly events\n\nA rotating event runs every week, announced in Discord and in game. Typical rotations include build battles, PvP tournaments, boss fights, parkour races and treasure hunts. Turn up at `/warp events` when the announcement goes out.\n\n## Build battles\n\n- Teams of one to four players.\n- A theme is announced at the start; the build time is fixed.\n- No schematics, no world edit, no copying another plot.\n- Players vote, staff break ties. Judging weighs originality, execution and fit to the theme.\n\n## Seasons\n\nEach season runs for a set number of weeks and ends with a full reset of the seasonal world. Ranks, cosmetics, purchased currencies and website stats always carry over. Seasonal leaderboards are archived and top finishers receive a permanent profile badge.\n\n## Leaderboards\n\nKills, playtime, balance and streaks are tracked live and shown on the website. Leaderboard abuse — kill farming with alts, AFK playtime machines — voids your placement and can end in a ban.', true, 22),

('discord', 'Discord and Account Linking', 'Community', 'Join the Discord, link your accounts, and get your rank roles synced automatically.',
E'Discord is where announcements, support and the community live.\n\n## Joining\n\nThe invite is on the website footer and in game via `/discord`.\n\n## Linking your account\n\n1. Sign in at [warden.rip](https://warden.rip).\n2. Open your profile settings.\n3. Choose **Link Discord** and approve the authorisation prompt.\n\nOnce linked, your rank role is applied automatically and updates whenever your rank changes. Unlinking removes the roles.\n\n## Channel guide\n\n- **announcements** — releases, events and maintenance windows.\n- **general** — open chat for everyone.\n- **support** — quick questions; anything needing account access goes to a website ticket.\n- **suggestions** — feature ideas with community voting.\n- **media** — screenshots, clips and builds.\n\n## Discord rules\n\nThe server rules apply in full. In addition: keep channels on topic, no DM advertising, and no pinging staff for issues that belong in a ticket.', true, 30),

('support', 'Getting Support', 'Community', 'Tickets, reports, appeals and what information to include so your issue is solved fast.',
E'Pick the right channel and your issue gets resolved in hours instead of days.\n\n## Which channel to use\n\n| Situation | Where to go |\n| --- | --- |\n| Purchase or rank problem | Website support ticket |\n| Someone is breaking rules | `/report` in game, or a website report |\n| You were punished unfairly | Website appeal form |\n| Quick question | Discord support channel |\n| Bug or exploit | Website ticket, marked as a bug |\n\n## What to include\n\n- Your exact Minecraft username\n- The date and approximate time, with your timezone\n- The game mode or world\n- Screenshots or video where relevant\n- The order reference for anything store related\n\n## Response times\n\nMost tickets get a first reply within 24 hours. Purchase issues are prioritised. Appeals are reviewed by an admin who was not involved in the original punishment.\n\n## Please do not\n\nOpen duplicate tickets, ping staff repeatedly, or argue a decision in public chat. All three slow your case down.', true, 31),

('staff-applications', 'Applying for Staff', 'Community', 'Requirements, what we look for, and how the application process runs.',
E'Staff applications open periodically and are announced in Discord.\n\n## Minimum requirements\n\n- 16 years or older\n- A working microphone and Discord account\n- No active or recent punishments\n- Regular playtime over the previous month\n- Able to commit a few hours per week consistently\n\n## What we look for\n\nCalm, consistent people. Technical knowledge can be taught; judgement under pressure and fairness cannot. Applications that read as copy-paste templates are rejected immediately.\n\n## The process\n\n1. Submit the form at [warden.rip/apply](https://warden.rip/apply).\n2. Shortlisted applicants receive a Discord interview invite.\n3. Successful candidates join a trial period with a mentor.\n4. Full staff is confirmed after the trial.\n\n## After a rejection\n\nYou can reapply when applications next open. Staying active, helpful and drama-free between rounds is the strongest thing you can do for the next application.', true, 32),

('troubleshooting', 'Troubleshooting and FAQ', 'Support', 'Fixes for connection failures, crashes, lag, lost items and account problems.',
E'The most common issues, with the fixes that actually work.\n\n## I cannot connect\n\n- Confirm the address is `play.warden.rip` with no typos or extra spaces.\n- Check the status page on the website before assuming it is your end.\n- Restart your launcher, then your router.\n- Remove the server and re-add it to clear a stale cached address.\n- If you see a ban message, use the appeal form.\n\n## The game is lagging\n\n- Low FPS is client side: lower render distance, turn off fancy graphics, and allocate 4–6 GB of RAM.\n- High ping is network side: use a wired connection and close background downloads.\n- Server-wide lag is announced in Discord — if others are fine, it is local.\n\n## Minecraft crashes on join\n\nCrashes are almost always mods. Launch vanilla first. If vanilla works, add mods back a few at a time to find the culprit. Optimisation mods from an old Minecraft version are the usual cause.\n\n## I lost items\n\nDeath loss is not refunded. Items lost to a confirmed server bug or rollback may be restored — open a ticket with the time, the world, and a screenshot or clip showing the items. Without evidence a restore cannot be approved.\n\n## I cannot sign in to the website\n\nUse the password reset link and check spam for the email. If you signed up with Google, sign in with Google rather than a password. Accounts created twice with the same email cannot be merged automatically — open a ticket.\n\n## My purchase has not arrived\n\nRanks activate instantly. Relog once. If it is still missing after five minutes, open a ticket with your order reference and it will be granted manually.', true, 40),

('banned-mods', 'Allowed and Banned Mods', 'Support', 'Which client mods are permitted, which are bannable, and the rule of thumb in between.',
E'The rule of thumb: if a mod shows you information you could not obtain in vanilla, or performs an action for you, it is banned.\n\n## Allowed\n\n- Performance mods such as Sodium, Lithium and Iris\n- Minimaps **without** entity or cave radar\n- Inventory sorting and crafting tweaks\n- Shaders and resource packs\n- Damage indicators and armour HUDs\n- Toggle sprint and sneak\n\n## Banned\n\n- Any combat assistance: killaura, aim assist, reach, hitboxes, velocity\n- Movement hacks: fly, speed, no-fall, jesus, spider\n- X-ray, cave finders, freecam and full-bright beyond gamma\n- Entity or player radar, including minimap radar modes\n- Autoclickers, macros and auto-fishing\n- Inventory movement automation such as chest stealers\n\n## Unsure about a mod\n\nAsk in the Discord support channel before you use it. A pre-approval takes a minute; a cheating ban is permanent.', true, 41);
